# Generated by Django 4.1.7 on 2023-06-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0002_remove_commpetition_numberofexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='minimum_numberOfExperience',
        ),
    ]
