# Generated by Django 4.1.7 on 2023-06-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0003_remove_bid_minimum_numberofexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
