# Generated by Django 4.1.7 on 2023-03-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_customer'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_services',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.admin')),
                ('service_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services')),
            ],
        ),
    ]
