# Generated by Django 4.1.7 on 2023-06-16 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('customer_ID', models.CharField(max_length=500, null=True)),
                ('app_date', models.DateField()),
                ('ApprovalStatus', models.CharField(default='pending', max_length=500, null=True)),
                ('pending', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dep_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.department')),
                ('service_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services')),
            ],
        ),
    ]
