# Generated by Django 4.1.7 on 2023-06-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_dep_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='service_ID',
            new_name='service_name',
        ),
    ]
